### ISSUE TITLE
Control Virtual Switches

### ISSUE THREAD

**Issue by JsChiSurf** [toggledbits/DeusExMachina#12]
Thanks for picking up this project and continuing with its development.

I still have a bunch of lights throughout my house that are still on x10.  Whenever something dies, I switch it to z-wave, so now, I'm at about 60/40 x10 to z-wave.

For the x10 lights, I still control them in my Vera via "virtual switches" that make HTTP calls to turn on/off the lights.  It would be great if these virtual switches showed up as options in the "lights to be controlled" configuration menu, so that I could add some of my legacy x10 lights / switches to the list of lights controlled by this plugin.

![virtual](https://cloud.githubusercontent.com/assets/3758371/18788579/0e9a108e-816d-11e6-8b04-6af4b81360d4.png)

**Comment by JsChiSurf** [comment]
After reviewing the code, I could see it would be relatively trivial to update to support virtual switches, so I went ahead and did so, tested, and is working perfectly in my local copy.  As such, I've uploaded fork / changes for the 2 affected files. 

Perhaps I am the only one who finds this of value, and if so, please feel free to ignore!

Thanks.

**Comment by toggledbits** [comment]
I don't see your branch, but then I'm a github n00b, so I'm probably not looking in the right place.

Since I've got a pending request for support of Philips Hue, I've been working on a generic solution for this, so it doesn't become a nest of hard-coded exceptions that requires a release every time a new device pops up. MiOS doesn't make that easy on the UI side, I'm finding. The API is a bit thin, and the documentation is crap, frankly. Fortunately, puzzles interest me.

**Comment by JsChiSurf** [comment]
Ah, I created a fork but didn't issue the pull request.  I did so now, so I'm guessing you should see, but if the code is in a revamp anyway, for a more "global" solution, perhaps it's a moot point.  Puzzles interest us all if you enjoy coding!

**Comment by toggledbits** [comment]
I see it now. Thanks!

**Comment by toggledbits** [comment]
Well, after trying to figure out something elegant, I decided to do what works, and come back to elegant later. If I could query a device to see if it implements the SwitchPower1 or Dimming1 service, that's a way to know if DEMII could control it. What I was hoping to find was a way in the JS API to see the service list for a device, but I don't see a way to do that. So, I'm instead probing for state variables known to exist in the Dimming1 and SwitchPower1 services, and if they're there, the device gets listed. This leads to some interesting side-effects. In my config, most of my motion sensors and my Nest meta-device are listed. The Nest device is OK--turning it on and off means "home" or "away." I'm guessing on/off for the motion sensors is related to arming, but I haven't tested that yet. But, I think this will solve the problem for any virtual switch device/plugin, and Philips Hue. I think it will even let you roll your shades up and down if you've got that! Anyway, if you're inclined to beta test, grab the head of the develop branch and upload it to your Vera. You should only need I_DeusExMachinaII1.xml and J_DeusExMachinaII1_UI7.js. Those are the only files changed since 2.3 was released. These new files also support running scenes at random intervals, which would be another way to deal with some devices.

**Comment by JsChiSurf** [comment]
Thanks.  Makes sense, and I think it is better to potentially offer too many that a user can choose to ignore, as opposed to potentially missing out on the opportunity to control things not even originally anticipated. It opens the door for even greater control of things not originally envisioned, which is pretty cool.  I'd be glad to test the development version, if it can be back-ported, since I'm unfortunately stuck on UI6 (your version working fine by the way), due to my alarm system not playing well with UI7 to date.
